# Generated by Django 4.0 on 2021-12-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
                ('preco', models.FloatField()),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
