# Generated by Django 4.0 on 2021-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
