# Generated by Django 4.0 on 2021-12-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
